definitions:
  handler.CompletionResponse:
    properties:
      data:
        items:
          type: integer
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  handler.Conversation:
    properties:
      id:
        description: Unique ID for the conversation
        type: string
      model:
        description: Model used for the conversation
        type: string
      userID:
        description: User ID associated with the conversation
        type: string
    type: object
  handler.ErrorResponse:
    description: Common error response format
    properties:
      error:
        example: Invalid input
        type: string
    type: object
  handler.GetAllChatResponse:
    description: Response containing all conversations for a user
    properties:
      conversations:
        items:
          $ref: '#/definitions/handler.Conversation'
        type: array
      message:
        type: string
      success:
        type: boolean
    type: object
  handler.GetChatByIDResponse:
    description: Response when a conversation is successfully retrieved
    properties:
      conversation:
        $ref: '#/definitions/handler.Conversation'
      message:
        type: string
      success:
        type: boolean
    type: object
  handler.Message:
    properties:
      content:
        type: string
      conversation_id:
        type: integer
      id:
        type: integer
      role:
        type: string
      timestamp:
        type: string
    type: object
  handler.completionsRequest:
    properties:
      content:
        type: string
      conversation_id:
        type: string
      model:
        type: string
      role:
        type: string
    required:
    - content
    - role
    type: object
  handler.deleteAllChatByUserIDResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  handler.deleteChatByIDResponse:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /chat/{conversation_id}:
    delete:
      description: Deletes the specified conversation and its associated messages
        from the database
      parameters:
      - description: Conversation ID
        in: path
        name: conversation_id
        required: true
        type: string
      responses:
        "200":
          description: Successfully deleted the conversation
          schema:
            $ref: '#/definitions/handler.deleteChatByIDResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Conversation not found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Delete a conversation by ID
    get:
      description: Retrieves a conversation from the database using its ID
      parameters:
      - description: Conversation ID
        in: path
        name: conversation_id
        required: true
        type: string
      responses:
        "200":
          description: Successfully retrieved the conversation
          schema:
            $ref: '#/definitions/handler.GetChatByIDResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Conversation not found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get a conversation by ID
  /chat/all:
    delete:
      description: Deletes all conversations and their associated messages for a given
        user
      responses:
        "200":
          description: Successfully deleted all conversations for the user
          schema:
            $ref: '#/definitions/handler.deleteAllChatByUserIDResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: No conversations found for the user
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete all conversations for a user
    get:
      description: Retrieves all conversations stored in the database
      responses:
        "200":
          description: Successfully retrieved all conversations
          schema:
            $ref: '#/definitions/handler.GetAllChatResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get all conversations
  /healthz:
    get:
      consumes:
      - application/json
      description: Check if the service is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - health
  /messages:
    get:
      consumes:
      - application/json
      description: Fetches all messages associated with a given conversation ID, ordered
        by timestamp.
      parameters:
      - description: Conversation ID
        in: body
        name: conversation_id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of messages in the conversation
          schema:
            items:
              $ref: '#/definitions/handler.Message'
            type: array
        "400":
          description: Invalid conversation ID
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Conversation not found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get all messages for a specific conversation
  /send-chat:
    post:
      consumes:
      - application/json
      description: Send a chat message to the completions API and receive a response.
      parameters:
      - description: Chat message request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.completionsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CompletionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Send chat message
      tags:
      - chat
swagger: "2.0"
